version: "{build}"

os: Visual Studio 2017

install:
  - git submodule update --init --recursive

build_script:
  - cmd: build\win\release.bat

test_script:
  - ps: build\win\test.ps1

artifacts:
  - path: build\win\libfly-win*.zip
    name: libfly-zips

deploy:
  - provider: GitHub

    force_update: true

    auth_token:
      secure: f6ku4Ps7AVm/2XvrZKSoRsFfZ6dmBRNZEzN47bbvvYtSP2oG4CxJTgAfH7GJa5ls

    artifact: libfly-zips

    on:
      appveyor_repo_tag: true
