trigger:
  branches:
    include:
    - master

  tags:
    include:
    - '*'

jobs:
  #### Linux Clang ####

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'clang'
      mode: 'Debug'
      arch: 'x86'

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'clang'
      mode: 'Debug'
      arch: 'x64'

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'clang'
      mode: 'Release'
      arch: 'x86'

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'clang'
      mode: 'Release'
      arch: 'x64'

  #### Linux GCC ####

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'gcc'
      mode: 'Debug'
      arch: 'x86'

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'gcc'
      mode: 'Debug'
      arch: 'x64'

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'gcc'
      mode: 'Release'
      arch: 'x86'

  - template: build/ci/linux.yml
    parameters:
      toolchain: 'gcc'
      mode: 'Release'
      arch: 'x64'

  #### macOS Clang ####

  - template: build/ci/macos.yml
    parameters:
      toolchain: 'clang'
      mode: 'Debug'

  - template: build/ci/macos.yml
    parameters:
      toolchain: 'clang'
      mode: 'Release'

  #### macOS GCC ####

  - template: build/ci/macos.yml
    parameters:
      toolchain: 'gcc'
      mode: 'Debug'

  - template: build/ci/macos.yml
    parameters:
      toolchain: 'gcc'
      mode: 'Release'

  #### Windows ####

  - template: build/ci/windows.yml
    parameters:
      mode: 'Debug'
      arch: 'x86'

  - template: build/ci/windows.yml
    parameters:
      mode: 'Debug'
      arch: 'x64'

  - template: build/ci/windows.yml
    parameters:
      mode: 'Release'
      arch: 'x86'

  - template: build/ci/windows.yml
    parameters:
      mode: 'Release'
      arch: 'x64'
