jobs:
  #### Linux ####
  - template: build/ci/nix_debug.yml
    parameters:
      name: Linux_Debug_x86
      arch: 'x86'

  - template: build/ci/nix_debug.yml
    parameters:
      name: Linux_Debug_x64
      arch: 'x64'

  - template: build/ci/nix_release.yml
    parameters:
      name: Linux_Release_x86
      arch: 'x86'

  - template: build/ci/nix_release.yml
    parameters:
      name: Linux_Release_x64
      arch: 'x64'

  #### Windows ####
  - template: build/ci/win_debug.yml
    parameters:
      name: Windows_Debug_x86
      arch: 'x86'

  - template: build/ci/win_debug.yml
    parameters:
      name: Windows_Debug_x64
      arch: 'x64'

  - template: build/ci/win_release.yml
    parameters:
      name: Windows_Release_x86
      arch: 'x86'

  - template: build/ci/win_release.yml
    parameters:
      name: Windows_Release_x64
      arch: 'x64'
