trigger:
  branches:
    include:
    - main

  tags:
    include:
    - '*'

stages:
  - stage: Linux
    dependsOn: []

    jobs:
      - template: build/ci/linux.yml
        parameters:
          toolchain: 'clang'
          mode: 'debug'
          arch: 'x86'

      - template: build/ci/linux.yml
        parameters:
          toolchain: 'clang'
          mode: 'debug'
          arch: 'x64'
          coverage: '1'

      - template: build/ci/linux.yml
        parameters:
          toolchain: 'clang'
          mode: 'release'
          arch: 'x86'

      - template: build/ci/linux.yml
        parameters:
          toolchain: 'clang'
          mode: 'release'
          arch: 'x64'

      - template: build/ci/linux.yml
        parameters:
          toolchain: 'gcc'
          mode: 'debug'
          arch: 'x86'

      - template: build/ci/linux.yml
        parameters:
          toolchain: 'gcc'
          mode: 'debug'
          arch: 'x64'

      - template: build/ci/linux.yml
        parameters:
          toolchain: 'gcc'
          mode: 'release'
          arch: 'x86'

      - template: build/ci/linux.yml
        parameters:
          toolchain: 'gcc'
          mode: 'release'
          arch: 'x64'

  - stage: macOS
    dependsOn: []

    jobs:
      - template: build/ci/macos.yml
        parameters:
          mode: 'debug'

      - template: build/ci/macos.yml
        parameters:
          mode: 'release'

  - stage: Windows
    dependsOn: []

    jobs:
      - template: build/ci/windows.yml
        parameters:
          mode: 'Debug'
          arch: 'x86'

      - template: build/ci/windows.yml
        parameters:
          mode: 'Debug'
          arch: 'x64'

      - template: build/ci/windows.yml
        parameters:
          mode: 'Release'
          arch: 'x86'

      - template: build/ci/windows.yml
        parameters:
          mode: 'Release'
          arch: 'x64'

  - stage: Release

    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

    dependsOn:
      - Linux
      - macOS
      - Windows

    jobs:
    - job: 'Release'
      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          downloadType: all
          artifactName: libfly
          downloadPath: $(System.ArtifactsDirectory)
        displayName: Download

      - task: GitHubRelease@0
        inputs:
          action: edit
          tag: $(Build.SourceBranchName)
          tagSource: 'Git tag'
          gitHubConnection: trflynn89
          repositoryName: trflynn89/libfly
          assets: $(System.ArtifactsDirectory)/libfly/*
          assetUploadMode: delete
        displayName: Publish
