trigger:
  branches:
    include:
    - master

  tags:
    include:
    - '*'

jobs:
  #### Linux ####

  - template: build/ci/linux.yml
    parameters:
      configuration: 'Debug'
      toolchain: 'clang'
      arch: 'x86'

  - template: build/ci/linux.yml
    parameters:
      configuration: 'Debug'
      toolchain: 'clang'
      arch: 'x64'

  - template: build/ci/linux.yml
    parameters:
      configuration: 'Debug'
      toolchain: 'gcc'
      arch: 'x86'

  - template: build/ci/linux.yml
    parameters:
      configuration: 'Debug'
      toolchain: 'gcc'
      arch: 'x64'

  - template: build/ci/linux.yml
    parameters:
      configuration: 'Release'
      toolchain: 'clang'
      arch: 'x86'

  - template: build/ci/linux.yml
    parameters:
      configuration: 'Release'
      toolchain: 'clang'
      arch: 'x64'

  #### Windows ####

  - template: build/ci/windows.yml
    parameters:
      configuration: 'Debug'
      arch: 'x86'

  - template: build/ci/windows.yml
    parameters:
      configuration: 'Debug'
      arch: 'x64'

  - template: build/ci/windows.yml
    parameters:
      configuration: 'Release'
      arch: 'x86'

  - template: build/ci/windows.yml
    parameters:
      configuration: 'Release'
      arch: 'x64'
