jobs:
  #### Ubuntu ####
  - job: Ubuntu
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        sudo apt-get install -y gcc-multilib g++-multilib
        git submodule update --init --recursive
      displayName: 'Setup'

    - script: build/nix/release.sh
      displayName: 'Build'

    - task: CopyFiles@2
      inputs:
        contents: 'build/nix/release-*/etc/libfly-*.tar.bz2'
        targetFolder: $(Build.ArtifactStagingDirectory)
        flattenFolders: true
      displayName: 'Collect'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: libfly
      displayName: 'Publish'

  #### Windows ####
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - script: |
        git submodule update --init --recursive
      displayName: 'Setup'

    - task: MSBuild@1
      inputs:
        solution: 'build\win\libfly.sln'
        maximumCpuCount: true
        configuration: 'Debug'
        platform: 'x64'
      displayName: 'Build debug x64'

    - task: MSBuild@1
      inputs:
        solution: 'build\win\libfly.sln'
        maximumCpuCount: true
        configuration: 'Debug'
        platform: 'x86'
      displayName: 'Build debug x86'

    - task: MSBuild@1
      inputs:
        solution: 'build\win\libfly.sln'
        maximumCpuCount: true
        configuration: 'Release'
        platform: 'x64'
      displayName: 'Build release x64'

    - task: MSBuild@1
      inputs:
        solution: 'build\win\libfly.sln'
        maximumCpuCount: true
        configuration: 'Release'
        platform: 'x86'
      displayName: 'Build release x86'

    - task: PowerShell@2
      inputs:
        filePath: build\win\test.ps1
      displayName: 'Test'

    - script: build\win\release.bat
      displayName: 'Package'

    - task: CopyFiles@2
      inputs:
        contents: 'build\win\libfly-*.zip'
        targetFolder: $(Build.ArtifactStagingDirectory)
        flattenFolders: true
      displayName: 'Collect'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: libfly
      displayName: 'Publish'
