jobs:
  #### Linux ####
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        sudo apt-get install -y gcc-multilib g++-multilib
        git submodule update --init --recursive
      displayName: 'Setup'

    - script: build/nix/release.sh
      displayName: 'Build'

    - task: CopyFiles@2
      inputs:
        contents: 'build/nix/release-*/etc/libfly-*.tar.bz2'
        targetFolder: $(Build.ArtifactStagingDirectory)
        flattenFolders: true
      displayName: 'Collect'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: libfly
      displayName: 'Publish'

  #### Windows ####
  - template: build/win/debug.yml
    parameters:
      name: Windows_Debug_x86
      arch: 'x86'

  - template: build/win/debug.yml
    parameters:
      name: Windows_Debug_x64
      arch: 'x64'

  - template: build/win/release.yml
    parameters:
      name: Windows_Release_x86
      arch: 'x86'

  - template: build/win/release.yml
    parameters:
      name: Windows_Release_x64
      arch: 'x64'
